src/Entity/Library.php
<?php

declare(strict_types=1);

namespace App\Entity;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="library")
 */
class Library
{
    /**
     * @var int
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    private $lat;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    private $lon;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $city;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $district;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $street;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $houseNumber;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $name;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    private $www;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="User")
     */
    private $user;

    /**
     * @var LibraryBook
     * @ORM\OneToMany(targetEntity="LibraryBook", mappedBy="library")
     */
    private $libraryBook;

    public function __construct()
    {
        $this->libraryBook = new ArrayCollection();
        $this->created_at = new \DateTime('now');
    }

    public function getBooks()
    {
        return $this->libraryBook->map(function (LibraryBook $libraryBook) {
            return $libraryBook->getBook();
        })->toArray();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getLat(): ?string
    {
        return $this->lat;
    }

    public function setLat(string $lat): void
    {
        $this->lat = $lat;
    }

    public function getLon(): ?string
    {
        return $this->lon;
    }

    public function setLon(string $lon): void
    {
        $this->lon = $lon;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): void
    {
        $this->street = $street;
    }

    public function getHouseNumber(): ?string
    {
        return $this->houseNumber;
    }

    public function setHouseNumber(string $houseNumber): void
    {
        $this->houseNumber = $houseNumber;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getWww(): ?string
    {
        return $this->www;
    }

    public function setWww(string $www): void
    {
        $this->www = $www;
    }

    public function getDistrict(): ?string
    {
        return $this->district;
    }

    public function setDistrict(string $district): void
    {
        $this->district = $district;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): void
    {
        $this->city = $city;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): void
    {
        $this->created_at = $created_at;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): void
    {
        $this->user = $user;
    }

    public function __toString()
    {
        return $this->getCity() . ' - ' . $this->getName();
    }
}

src/Controller/Api/LibraryController.php
<?php


namespace App\Controller\Api;


use App\Entity\Library;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Serializer\SerializerInterface;

class LibraryController extends AbstractController
{
    /**
     * @Route("/api/libraries")
     */
    public function list(EntityManagerInterface $entityManager, SerializerInterface $serializer)
    {
        $libraries = $entityManager
            ->getRepository(Library::class)
            ->findAll();

        $librariesInJson = $serializer->serialize(['data' => $libraries], 'json');

        return new Response($librariesInJson);
    }

    /**
     * @Route("/api/libraries/{id}")
     */
    public function show(Library $library, EntityManagerInterface $entityManager, SerializerInterface $serializer)
    {
        $librariesInJson = $serializer->serialize(['data' => [$library]], 'json');

        return new Response($librariesInJson);
    }
}

src/Controller/LibraryController.php
<?php


namespace App\Controller;

use App\Entity\Library;
use App\Form\LibraryFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class LibraryController extends AbstractController
{
    /**
     * @Route("/biblioteki/nowa")
     */
    public function create(Request $request, EntityManagerInterface $entityManager)
    {
        $form = $this->createForm(LibraryFormType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $library = $form->getData();

            $entityManager->persist($library);
            $entityManager->flush();

            $this->addFlash('success','Świetnie! Dodałeś nową bibliotekę :)');

            return $this->redirectToRoute('app_library_list');
        }

        return $this->render('library/create.html.twig' , [
                'libraryForm' => $form->createView()
            ]);
    }

    /**
     * @Route("/biblioteki")
     */
    public function list()
    {
        return $this->render('library/list.html.twig');
    }

    /**
     * @Route("/biblioteki/{id}")
     */
    public function show(Library $library, NormalizerInterface $normalizer)
    {
        $library = $normalizer->normalize($library);

        return $this->render('library/show.html.twig', [
            'library' => $library
        ]);
    }
}

templates/library/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="text-center">Dodaj bibliotekę</h1>

<div class="container">
    <div class="row">
        <div class="col-sm">
            {{ form_start(libraryForm) }}

            {{ form_row(libraryForm.name, {
                label: 'Nazwa'
            }) }}

            {{ form_row(libraryForm.city, {
                label: 'Miasto'
            }) }}

            {{ form_row(libraryForm.district, {
                label: 'Dzielnica'
            }) }}

            {{ form_row(libraryForm.street, {
                label: 'Ulica'
            }) }}

            {{ form_row(libraryForm.houseNumber, {
                label: 'Numer Ulicy'
            }) }}

            <button type="submit" class="btn btn-primary" formnovalidate> Dodaj</button>
            {{ form_end(libraryForm) }}
        </div>
        </div>
</div>
{% endblock %}

templates/library/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {%  for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <div class="text-center">
        <span> Nie ma twojej biblioteki na liście? To ją dodaj -> <a href="{{ path('app_library_create') }}">Kliknij tutaj aby dodać bibliotekę</a></span>
    </div>

    <div class="container">
        <div class="row">
            <table id="table_id" class="display">
                <thead>
                <tr>
                    <th></th>
                    <th>Nazwa</th>
                    <th>Miasto</th>
                    <th>Dzielnica</th>
                    <th>Ulica</th>
                </tr>
                </thead>
            </table>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function () {
            var t = $('#table_id').DataTable({
                "ajax": "{{ path('app_api_library_list') }}",
                "columns": [
                    {data: null},
                    {
                        mData: function (data) {
                            return "<a href=/biblioteki/" + data.id + '>' +  data.name + '</a>';
                        }
                    },
                    {
                        mData: function (data) {
                            return data.city;
                        }
                    },
                    {
                        mData: function (data) {
                            return data.district;
                        }
                    },
                    {
                        mData: function (data) {
                            return data.street + ' ' + data.houseNumber;
                        }
                    },
                ],
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/Polish.json"
                },
                "bPaginate": false,
                "dom": 'lifrtp'
            });

            t.on('order.dt search.dt', function () {
                t.column(0, {search: 'applied', order: 'applied'}).nodes().each(function (cell, i) {
                    cell.innerHTML = i + 1;
                });
            }).draw();
        });
    </script>
{% endblock %}

templates/library/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <div class="text-center">
        <span><a href="{{ path('app_book_create') }}">Kliknij tutaj aby dodać książkę</a></span>
    </div>

    <div class="container">
        <div class="row">
            <div>
                <strong>nazwa: </strong> {{ library.name }} <br>
                <strong>miasto: </strong> {{  library.city }} <br>
                <strong>ulica: </strong> {{ library.street }} {{ library.houseNumber }}
            </div>
        </div>
        <div class="row">
            <table id="table_id" class="display">
                <thead>
                <tr>
                    <th></th>
                    <th>Tytuł</th>
                    <th>Autor</th>
                    <th>Rok</th>
                    <th>Info</th>
                    <th>Nazwa Użytkownika</th>
                    <th>Data Dodania</th>
                </tr>
                <tbody>
                {% for book in library.books %}
                <tr>
                    <td></td>
                    <td> {{ book.title }} </td>
                    <td> {{ book.author }} </td>
                    <td> {{ book.year }}</td>
                    <td> {{ book.info }}</td>
                    <td> {{ book.user ? book.user.name : '' }}</td>
                    <td> {{ book.createdAt|date('m/d/Y') }}</td>
                </tr>
                {% endfor %}
                </tbody>
                </thead>
            </table>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function () {
            var t = $('#table_id').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/Polish.json"
                },
                "bPaginate": false,
                "dom": 'lifrtp'
            });

            t.on('order.dt search.dt', function () {
                t.column(0, {search: 'applied', order: 'applied'}).nodes().each(function (cell, i) {
                    cell.innerHTML = i + 1;
                });
            }).draw();
        });
    </script>
{% endblock %}